security:
    encoders:
        App\Entity\Usuario: plaintext


    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    providers:
        user_db:
            entity: { class: App\Entity\Usuario, property: codigoUsuarioPk }

    firewalls:
        main:
            pattern: /.*
            provider: user_db
            guard:
                authenticators:
                    - App\Controller\Seguridad\TokenAuthenticator
            form_login:
                login_path: /login
                check_path: /login
                remember_me: false
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true

    access_control:
        - { path: /api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /general/api/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /movimiento/api/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_FULLY }
