<?php

namespace App\Repository;

/**
 * TareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoRepository extends \Doctrine\ORM\EntityRepository
{
    public function apiLista( $codigoDocumento, $numero ) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->from( "App:Archivo", "a" )
            ->select( "a.codigoArchivoPk" )
            ->addSelect( "a.tipo" )
            ->addSelect( "a.extension" )
            ->addSelect( "a.tamano" )
            ->addSelect( "a.nombre" )
            ->addSelect( "a.nombreAlmacenamiento" )
            ->where( "a.codigoDocumentoFk = {$codigoDocumento}" )
            ->andWhere("a.numero = {$numero}");


        return $qb->getQuery()->getResult();
    }

    public function apiArchivoDescargar($codigoArchivo ) {
        $em  = $this->getEntityManager();
        $qb  = $em->createQueryBuilder();
        $qb->from( "App:Archivo", "a" )
            ->select( "a.nombre" )
            ->addSelect( "a.nombreAlmacenamiento" )
            ->addSelect( "a.tamano" )
            ->addSelect( "a.extension" )
            ->addSelect( "a.tipo" )
            ->where( "a.codigoArchivoPk = {$codigoArchivo}" );
        return $qb->getQuery()->getResult();
    }

}
