<?php

namespace App\Repository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends \Doctrine\ORM\EntityRepository
{
	public function listarAreas(){

		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		$qb->from("App:Area", "a")
			->select("a.codigoAreaPk")
			->addSelect("a.nombre");
		return $qb->getQuery()->getResult();
	}
}
