<?php

namespace App\Repository;

/**
 * CargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoRepository extends \Doctrine\ORM\EntityRepository{

	public function listarCargos(){

		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		$qb->from("App:Cargo", "a")
		   ->select("a.codigoCargoPk")
		   ->addSelect("a.nombre");
		return $qb->getQuery()->getResult();
	}
}
