<?php

namespace App\Repository;

use App\Entity\Configuracion;

/**
 * CasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionRepository extends \Doctrine\ORM\EntityRepository
{
    public function envioCorreo()
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()->from(Configuracion::class, 'c')
            ->select('c.codigoConfiguracionPk')
            ->addSelect('c.correoEmpresa')
            ->where('c.codigoConfiguracionPk = 1');
        return $queryBuilder->getQuery()->getSingleResult();

    }
}