<?php

namespace App\Repository;

/**
 * DevolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevolucionRepository extends \Doctrine\ORM\EntityRepository
{
}
