<?php

namespace App\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;

/**
 * CasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImplementacionRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return string
     */
    public function listaDql()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder()->from("App:Implementacion", "i")->select("i")
            ->where("i.codigoImplementacionPk <> 0")
            ->orderBy("i.codigoImplementacionPk", "DESC");
        $dql = $qb->getDQL();
        return $dql;
    }

    public function apiLista($codigoCliente)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder()->from("App:Implementacion", "i")
            ->select("i.codigoImplementacionPk")
            ->addSelect("c.nombreComercial")
            ->addSelect("i.descripcion")
            ->join("i.clienteRel", "c")
            ->where("i.codigoClienteFk = {$codigoCliente}");

        return $qb->getQuery()->getResult();

    }

    public function apiCabezera($codigoImplementacion)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder()->from("App:Implementacion", "i")
            ->select("i.codigoImplementacionPk")
            ->addSelect("c.nombreComercial")
            ->addSelect("i.descripcion")
            ->join("i.clienteRel", "c")
            ->where("i.codigoImplementacionPk = {$codigoImplementacion}");

        return $qb->getQuery()->getResult();

    }
}