<?php

namespace App\Repository;

/**
 * LlamadaCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LlamadaCategoriaRepository extends \Doctrine\ORM\EntityRepository {


}
