<?php

namespace App\Repository;

/**
 * ModuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuloRepository extends \Doctrine\ORM\EntityRepository
{
}
