<?php

namespace App\Repository;

/**
 * TareaTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudTipoRepository extends \Doctrine\ORM\EntityRepository
{
    public function listar()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->from("App:SolicitudTipo", "st")
            ->select("st.codigoSolicitudTipoPk")
            ->addSelect("st.nombre");
        return $qb->getQuery()->getResult();
    }

}
