<?php

namespace App\Repository;
use App\Entity\TareaTiempo;

/**
 * TareaTiempoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareaTiempoRepository extends \Doctrine\ORM\EntityRepository
{

    public function registroTiempoTareaInicio($arTarea,$codigoUsuario){
        $em = $this->getEntityManager();
        $tareaTiempo = new TareaTiempo();
        $tareaTiempo->setCodigoUsuarioFk($codigoUsuario);
        $tareaTiempo->setFechaHoraInicio(new \DateTime('now'));
        $tareaTiempo->setCodigoTareaFk($arTarea->getCodigoTareaPk());
        $em->persist($tareaTiempo);
        $em->flush();
        return $tareaTiempo->getCodigoTareaTiempoPk();
    }

    public function registroTiempoTareaFin($arTarea){
        $em = $this->getEntityManager();
        $tareaTiempo = $arTarea->getTareaTiempoRel();
        if($arTarea->getTareaTiempoRel()){
            $tareaTiempo->setFechaHoraFin(new \DateTime('now'));
            $diff = $tareaTiempo->getFechaHoraInicio()->diff($tareaTiempo->getFechaHoraFin());
            $minutos = ( ($diff->d * 24 ) * 60 ) + ($diff->h*60) + ( $diff->i );
            $tareaTiempo->setMinutos($minutos);
            $arTarea->setCodigoTareaTiempoFk(null);
            $em->persist($tareaTiempo);
            $em->persist($arTarea);
            $em->flush();
        }
}

}